---
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile-api
    env_file: .env
    image: eos-api:latest
    ports:
      - "5000:5000"
    networks:
      - eos
    depends_on:
      - bot
    restart: unless-stopped

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile-bot
    env_file: .env
    image: eos-bot:latest
    networks:
      - eos
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    env_file: .env
    image: eos-postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - eos
    restart: unless-stopped
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  eos:
    driver: bridge
